### ISSUE TITLE
gas is not detected

### ISSUE THREAD

**Issue by mschweig** [DFRobot/DFRobot_MICS#1]
Hello, 

I am using SEN0377 on raspberry pi and I am only getting after succesfull calibration "gas concentration is: 0.0" 

Tried with different gases.

How can I solve this?

**Comment by zeroistfilm** [comment]
you must contain "warmUp" code.
``` C
 while(!mics.warmUpTime(CALIBRATION_TIME)){
    Serial.println("Please wait until the warm-up time is over!");
    delay(1000);
  }
```
`mics.warmUpTime` setup  `__r0_red` and `__r0_ox`  value for calculrating `RS_R0_RED_data`, `RS_R0_OX_data`

**Comment by dimitra-kouvara** [comment]
i have the same issue. i use SEN0377 with ESP32 and after the warm up i get 0.0 PPM in all gases. 
is there a solution?

**Comment by zeroistfilm** [comment]
I got 0.0 PPM on normal conditions.  could you burn an incense stick (to make smoke).  
if the sensor with smoke, I got some value from the sensor.

**Comment by dimitra-kouvara** [comment]
tried that still getting 0 :(

**Comment by zeroistfilm** [comment]
can you have some data on `getADCdata` example?

Don't forget you set up i2c address. 

```
#include "DFRobot_MICS.h"

// When using I2C communication, use the following program to construct an object by DFRobot_MICS_I2C
/**
 * select i2c device address 
 * MICS_ADDRESS_0               0x75
 * MICS_ADDRESS_1               0x76
 * MICS_ADDRESS_2               0x77
 * MICS_ADDRESS_3               0x78
 */
#define MICS_I2C_ADDRESS MICS_ADDRESS_0
DFRobot_MICS_I2C mics(&Wire, 0x75);

void setup() 
{
  Serial.begin(115200);
  while(!Serial);
  while(!mics.begin()){
    Serial.println("NO Deivces !");
    delay(1000);
  }
  Serial.println("Device connected successfully !");

  uint8_t mode = mics.getPowerState();
  if(mode == SLEEP_MODE){
    mics.wakeUpMode();
    Serial.println("wake up sensor success!");
  }else{
    Serial.println("The sensor is wake up mode");
  }
}

void loop() 
{
  float  ox_data  = 0;
  float  red_data = 0;
  ox_data = mics.getADCData(OX_MODE);
  red_data = mics.getADCData(RED_MODE);
  Serial.print("ox  data = ");
  Serial.print( ox_data ); 
  Serial.print(" red data = ");
  Serial.println(red_data); 
  delay(1000);
}
```

**Comment by dimitra-kouvara** [comment]
I executed your code and got this results:
![adc_data](https://user-images.githubusercontent.com/71871533/177318777-586d9712-c672-4e3a-966f-d50f2d5155ec.png)
what does it mean?

**Comment by zeroistfilm** [comment]
it is mean that your sensor is ok.

this is my code. it it work for me.
![image](https://user-images.githubusercontent.com/47134564/177324377-e87ec225-6803-47fd-bbcc-1adc80dded90.png)
![image](https://user-images.githubusercontent.com/47134564/177324410-0f7d8550-d118-447c-bcf0-436af04ad5c0.png)

```
#include "DFRobot_MICS.h"
#define CALIBRATION_TIME   1      


DFRobot_MICS_I2C mics(&Wire, 0x75);


void setup() {
  // put your setup code here, to run once:
  Serial.begin(115200);

  while(!mics.begin()){
    Serial.println("NO Deivces !");
    delay(1000);
  } Serial.println("Device connected successfully !");
  
  uint8_t mode = mics.getPowerState();
  if(mode == SLEEP_MODE){
    mics.wakeUpMode();
    Serial.println("wake up sensor success!");
  }else{
    Serial.println("The sensor is wake up mode");
  }
  while(!mics.warmUpTime(CALIBRATION_TIME)){
    Serial.println("Please wait until the warm-up time is over!");
    delay(1000);
  }

}

void loop() {
  // put your main code here, to run repeatedly:


  float ch4 = mics.getGasData(CH4);
  float c2h5oh = mics.getGasData(C2H5OH);
  float h2 = mics.getGasData(H2);
  float nh3 = mics.getGasData(NH3);
  float co = mics.getGasData(CO);
  float no2 = mics.getGasData(NO2);
  

  
  Serial.print(ch4);
  Serial.println(" PPM ch4");

  Serial.print(c2h5oh);
  Serial.println(" PPM c2h5oh");

  Serial.print(h2);
  Serial.println(" PPM h2");

  Serial.print(nh3);
  Serial.println(" PPM nh3");

  Serial.print(co);
  Serial.println(" PPM co");

  Serial.print(no2);
  Serial.println(" PPM no2");
 

  delay(1000);

  
}

```

**Comment by dimitra-kouvara** [comment]
tried your code. i still get 0 values, even with smoke present in the area. 
![image](https://user-images.githubusercontent.com/71871533/177482627-c11b6f6b-ff3f-4850-b3ce-12c0398c997d.png)

**Comment by ushalvn6** [comment]
Hi, did anyone manage to solve this issue?

**Comment by zeroistfilm** [comment]
It is not the best choice to detect gas. 
I recommend other sensors type of electrochemical.

**Comment by 96liuzhixin** [comment]
If you only need a higher concentration to detect the presence of gas, when the concentration is higher, there is a response, but the lower concentration does not respond, it is recommended to replace the sensor.
